# ruff.toml
[lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "N",   # pep8-naming
    "B",   # flake8-bugbear
    "ARG", # unused arguments
]

# This bans making lowercase imports uppercase, which seems silly.
ignore = ["F401"]

# Specifically target unused arguments
per-file-ignores = {"__init__.py" = ["F401"]} # ignore unused imports in __init__.py files